/**
 * Taking the descriptions away with you.
 *
 * A described timeline is the expensive part of this project — several minutes
 * of processing and a run of Gemma calls — and until now it only existed inside
 * one browser tab. These two formats cover what it is actually wanted for:
 *
 *  - **Text** for studying and for revision, and for a screen reader to read
 *    straight through at whatever speed the learner prefers.
 *  - **WebVTT** because it is the standard description track: it loads in a
 *    real player, and any tool that speaks subtitles will speak these.
 *
 * Both are generated in the browser from the timeline already in memory, so
 * neither costs a request, and neither can go stale against what is on screen.
 */

/** `93.4` -> `00:01:33.400` — WebVTT insists on all three parts. */
function vttStamp(seconds) {
  const total = Math.max(0, Number(seconds) || 0);
  const hours = Math.floor(total / 3600);
  const minutes = Math.floor((total % 3600) / 60);
  const secs = Math.floor(total % 60);
  const millis = Math.round((total - Math.floor(total)) * 1000);
  const pad = (n, width = 2) => String(n).padStart(width, '0');
  return `${pad(hours)}:${pad(minutes)}:${pad(secs)}.${pad(millis, 3)}`;
}

/** `93` -> `1:33`, matching the timestamps shown in the list. */
function shortStamp(seconds) {
  const total = Math.max(0, Math.floor(Number(seconds) || 0));
  const hours = Math.floor(total / 3600);
  const minutes = Math.floor((total % 3600) / 60);
  const secs = total % 60;
  const pad = (n) => String(n).padStart(2, '0');
  return hours ? `${hours}:${pad(minutes)}:${pad(secs)}` : `${minutes}:${pad(secs)}`;
}

/** A filename that survives every filesystem, derived from the video title. */
export function safeFileName(title, extension) {
  const base = String(title || 'shruti-descriptions')
    .replace(/[\/:*?"<>|]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 80);
  return `${base || 'shruti-descriptions'}.${extension}`;
}

/**
 * A plain-text transcript of the descriptions, with a short header saying what
 * the file is — a bare list of timestamps is a puzzle a week later.
 */
export function descriptionsToText(descriptions, meta = {}) {
  const lines = [];
  if (meta.title) lines.push(meta.title);
  lines.push('Audio descriptions prepared by Shruti.');
  if (meta.model) lines.push(`Generated by ${meta.model}.`);
  if (meta.language) lines.push(`Language: ${meta.language}.`);
  if (meta.url) lines.push(meta.url);
  lines.push('');

  descriptions.forEach((entry) => {
    const kind = entry.mode === 'explain' ? ' [full explanation]' : '';
    lines.push(`[${shortStamp(entry.time)}]${kind} ${entry.description}`);
    lines.push('');
  });

  return lines.join('\n');
}

/**
 * A WebVTT description track.
 *
 * Each cue runs until the next one starts, capped at twelve seconds so a
 * description does not sit on screen for a whole quiet stretch; the last cue
 * gets a fixed six seconds because there is nothing after it to bound it.
 */
export function descriptionsToVtt(descriptions, meta = {}) {
  const header = ['WEBVTT', ''];
  if (meta.title) header.push(`NOTE ${meta.title}`, '');
  header.push('NOTE Audio descriptions prepared by Shruti.', '');

  const cues = descriptions.map((entry, index) => {
    const next = descriptions[index + 1];
    const gap = next ? next.time - entry.time : 6;
    const end = entry.time + Math.max(2, Math.min(12, gap - 0.2));
    return [
      String(index + 1),
      `${vttStamp(entry.time)} --> ${vttStamp(end)}`,
      entry.description,
      '',
    ].join('\n');
  });

  // A blank line has to separate the last NOTE block from the first cue, or a
  // strict parser reads the cue as part of the comment.
  return [header.join('\n'), cues.join('\n')].join('\n');
}

/**
 * Hand a generated string to the browser as a download.
 *
 * The object URL is revoked on the next tick rather than immediately: some
 * browsers have not finished reading the blob when `click()` returns, and
 * revoking too early produces an empty file.
 */
export function downloadText(filename, mimeType, content) {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.rel = 'noopener';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 0);
}
